[package]
name = "rust-buildpack-example-actix"
version = "0.1.0"
authors = ["Eric Kidd <git@randomhacks.net>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.1.1"
actix = "0.10.0-alpha.3"
actix-files = "0.3.0"